### ISSUE TITLE
UI Custom Icon Font

### ISSUE THREAD

**Issue by Qingyu510** [SethClydesdale/code-vein-builder#46]
When using Chinese translation, the font used is Japanese. Can you customize the port?
Sorry, I don't know how to create web pages

I decompressed the game and obtained a custom icon font.
This is the custom icon before the skill name

**Comment by Qingyu510** [comment]
![屏幕截图 2023-09-23 222618](https://github.com/SethClydesdale/code-vein-builder/assets/63525216/8fdb0327-48ca-4a0e-b6d5-095ebc047718)

I hope to add a translation font port
![屏幕截图 2023-09-23 222812](https://github.com/SethClydesdale/code-vein-builder/assets/63525216/4e3ae7fb-312c-4a24-b07e-6634fe92169e)
My English is not very good, I'm sorry

**Comment by SethClydesdale** [comment]
Hello @Qingyu510!

You can import the font into the webpage by adding the following into the stylesheet [here](https://github.com/SethClydesdale/code-vein-builder/blob/master/resources/css/main.css#L12).
```css
@font-face {
  font-family:'GEZFont';
  src:url('../fonts/GEZFont_UICustomIcon.ttf') format('truetype');
  font-weight:normal;
  font-style:normal;
}
```

Afterwards, you can utilize the font on different elements on the page, such as `body` for example:
```css
body {
  font-family:GEZFont;
}
```

The current font stack for the webpage is located [here](https://github.com/SethClydesdale/code-vein-builder/blob/60aeb794d1f652dc65d25f7022471948596bbd0a/resources/css/main.css#L32). If you want to apply different fonts for different languages, you can use the custom language classes on the body, such as for Chinese:
```css
body.lang-zh-hant {
  font-family: ... ;
}
```
This will override the default font-family if the font is supported on the user's system.
